### ISSUE TITLE
Apple keyboards don't all have the ⌥ symbol on them any more.

### ISSUE THREAD

**Issue by johnhorner** [jgthms/javascript-in-14-minutes#2]
JS in 14 minutes tells me to use the ⌥, ⌘ and J keys.

My relatively new Apple laptop doesn't have the "train-switching-tracks" symbol on the **option** key. It just says **option** and **alt** in smaller letters.

<img width="426" alt="Screen shot" src="https://user-images.githubusercontent.com/3282426/38017369-925570b4-32bd-11e8-8268-704977e5f269.png">

![apple-11q3-wirelesskeyboard-top-lg](https://user-images.githubusercontent.com/3282426/38017563-21a38634-32be-11e8-8aa7-73463831e421.jpg)

**Comment by jgthms** [comment]
Funnily enough, I have that _exact_ same keyboard, and didn't think about that! It's an easy fix.

**Comment by jgthms** [comment]
Fixed!
