### ISSUE TITLE
I couldn't make it work in my local machine

### ISSUE THREAD

**Issue by camilomontoyau** [jgthms/javascript-in-14-minutes#8]
Hi Jeremy @jgthms, I'm about to translate it to spanish, but I couldn't make it work in my local.
it seems you're using some javascript template engine (mustache, handlebars or something similar), but I didn't see any dependency related in package.json

When I do npm start I see the css and js builds and outputs, but I don't see any html output

What am I missing?

Could you please help me? 

Thanks

![js-14-min](https://user-images.githubusercontent.com/5333383/48007685-286afc00-e0e6-11e8-8998-1c8ecb6bc25e.gif)

**Comment by jgthms** [comment]
You need Jekyll to run it: https://jekyllrb.com/

**Comment by camilomontoyau** [comment]
thanks, it worked!!
